apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-secret
  labels:
    app: jupyterhub
    version: v1
    component: application
type: Opaque
data:
  # Пароль 'any-password' в base64
  JUPYTERHUB_PASSWORD: YW55LXBhc3N3b3Jk