apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-service
  labels:
    app: jupyterhub
    version: v1
    component: application
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: jupyterhub