apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    version: v1
    component: proxy
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: nginx