apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    version: v1
    component: database
type: Opaque
stringData:
  POSTGRES_USER: "jupyterhub"
  POSTGRES_PASSWORD: "jupyterhub_password"