apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    version: v1
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres