apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    version: v1
    component: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis